name: Test and Deploy

on:
  push:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -o pr-discord-notifier -v ./...
      - name: Test
        run: go test -v
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.HOST }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Deploy files to host with rsync
        run: rsync -avz ./pr-discord-notifier ${{ secrets.USER}}@${{ secrets.HOST }}:~/pr-discord-notifier
      - name: Updating pr-discord-notifier service to run latest binary
        run: ssh -t ${{ secrets.USER}}@${{ secrets.HOST}} 'sudo systemctl enable pr-discord-notifier && sudo systemctl restart pr-discord-notifier'
